language: rust

env:
    global:
        - CRATE_NAME=dtparse

matrix:
    include:
        # Tests will only run on nightly, and where I can install Python/Dateutil
        # Should still build on stable though
        - env: TARGET=aarch64-unknown-linux-gnu
          rust: nightly
        - env: TARGET=x86_64-unknown-linux-gnu
          rust: nightly
        - env: TARGET=x86_64-unknown-linux-musl
          rust: nightly

before_install:
    - set -eu
    - pip install dateutil
    - rustup self update

