language: rust

jobs:
  include:
  - rust: stable
    os: linux
  - rust: 1.28.0
    os: linux
    env: DISABLE_TOOLS=true
  - rust: stable
    os: osx
  - rust: stable-msvc
    os: windows
  - rust: stable
    os: windows

cache:
  - cargo

before_script:
  - rustup show
  # CMake doesn't like the `sh.exe` provided by Git being in PATH
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then rm "C:/Program Files/Git/usr/bin/sh.exe"; fi
  - if [[ "$DISABLE_CLIPPY" == "" ]]; then rustup component add clippy; rustup component add rustfmt; fi

script:
  - if [[ "$DISABLE_CLIPPY" == "" ]]; then cargo clippy --all && cargo fmt --all -- --check; fi

  # For default build, split up compilation and tests so we can track build times
  - cargo test --no-run
  - cargo test
  - cargo test --release --no-run
  - cargo test --release

branches:
  only:
    - master
    - staging
    - trying
    
