[package]
name = "dtparse"
version = "0.1.0"
authors = ["Bradlee Speice <bspeice@kcg.com>"]

[dependencies]
chrono = "0.4"
lazy_static = "*"
num-traits = "0.2"
rust_decimal = "0.8"

[dev-dependencies]
pyo3 = "0.2"